config/routes.rb
Zhidak::Application.routes.draw do
  resources :comments, only: [:new, :create]

  root 'home#index'

  get 'posts' => 'home#posts', as: 'posts'
  get 'post/(:id)' => 'home#post', as: 'post'
  get 'price' => 'home#price', as: 'price'
  get 'contact' => 'home#contact', as: 'contact'
  get 'about' => 'home#about', as: 'about'
  get 'case' => 'home#case', as: 'case'
  get 'channel/(:id)' => 'home#channel', as: 'channel'
  get 'portfolio' => 'home#portfolio', as: 'portfolio'

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  self.table_name = 'admin_channels'

  has_many :pages, dependent: :destroy
  has_many :children, class_name: "Channel",
                          foreign_key: "parent_id",
                          dependent: :destroy
  belongs_to :parent, class_name: "Channel"

  def get_image_path
    if image_path
      'http://admin.zhidak.com/' + image_path
    else
      '/assets/logo-1.png'
    end
  end

  def get_content
    if content
      begin
        the_content = content.gsub(/src="(\/ckeditor_assets\/pictures\/\d+\/)/, 'class="image fit max800" src="http://admin.zhidak.com/\1')
        the_content = the_content.gsub(/<h3>/i, '<h3><i class="fa fa-dot-circle-o fa-lg"></i> ')
      rescue => ex
        logger.error 'page parser: ' + ex.message
        '页面解析有错'
      end
    else
      '没有任何内容'
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  self.table_name = 'admin_comments'

  #empty
  validates :mobile_phone, presence: true
  #length
  validates :mobile_phone, length: { is: 11 }
  #format
  validates :mobile_phone, format: { with: /\A1(3|5|6|7|8|9)[0-9]{9}\z/, message: "请输入正确的手机号码" }

  STATUS = %w[未处理 已处理 垃圾信息]
end

app/models/page.rb
class Page < ActiveRecord::Base
  self.table_name = 'admin_pages'

  default_scope { order('updated_at DESC') }

  belongs_to :channel
  self.per_page = 18

  def get_image_path
    if image_path
      'http://admin.zhidak.com/' + image_path
    else
      '/assets/logo-1.png'
    end
  end

  def get_content
    if content
      begin
        the_content = content.gsub(/src="(\/ckeditor_assets\/pictures\/\d+\/)/, 'class="image fit max800" src="http://admin.zhidak.com/\1')
        the_content = the_content.gsub(/<h3>/i, '<h3><i class="fa fa-dot-circle-o fa-lg"></i> ')
      rescue => ex
        logger.error 'page parser: ' + ex.message
        '页面解析有错'
      end
    else
      '没有任何内容'
    end
  end

  def short_description(count = 50)
    self.description.to_s.truncate(count)
  end

  def format_date
    self.updated_at.strftime("%Y-%m-%d") unless self.updated_at.nil?
  end

  def thumb_image_path
    self.image_path.sub(/content/, 'thumb')
  end

  # "H|C|F" => ['H', 'C', 'F']
  # 用于在_form.html.erb中初始化值
  def arr_properties
    properties.to_s.split('|')
  end

  #最近新闻
  #params:
  # => typo = ['article', 'image', 'product']
  # => channel =[ channel.short_title, ]
  # => properties =[recommend, top, hot]
  #eg: Admin::Page.recent(12, :typo => 'product',  :rand => true)
  #    Admin::Page.recent(10, :channel => 'product-bed', :properties => '1')
  def self.recent(count = 10, options = {})
    queries     = []
    conditions  = []
    if options[:channel].present?
      queries     << 'admin_channels.short_title = ?'
      conditions  << options[:channel]
    end
    if options[:typo].present?
      queries     << 'admin_channels.typo = ?'
      conditions  << options[:typo]
    end
    if options[:properties].present?
      queries     << 'admin_pages.properties regexp ?'
      conditions  << options[:properties]
    end
    conditions.unshift(queries.join(' AND '))
    return Page.joins(:channel).where(conditions).order("updated_at DESC").limit(count)
  end

  #搜索
  def self.search(search)
    if search
      where('title LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
    def mobile_device?
      request.user_agent =~ /Mobile|webOS/
    end
    helper_method :mobile_device?
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        if Rails.env == 'production' && filter_backlist(@comment)
          SmsSendWorker.perform_async(ENV['ADMIN_PHONE'].split('|').join(','), "【直达客】#{@comment.mobile_phone}留言：#{@comment.content.to_s.truncate(36)}")
        end
        format.html { redirect_to contact_path, notice: '信息提交成功，我们会尽快回复您的请求.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:name, :mobile_phone, :email, :qq, :address, :content, :status)
    end

    def filter_backlist(cmt)
      return false if cmt.mobile_phone.blank? || cmt.content.blank?
      return false if cmt.mobile_phone !~ /^1\d{10}$/
      return false if cmt.content =~ /(http:|www)/i
      return true
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #@portfolios = Page.recent(12, :channel => 'portfolio')
    @portfolios = Channel.find_by(short_title: 'portfolio').children
    @cases = Page.recent(6, :channel => 'case')
    @about = Page.find_by(short_title: 'about')
    @about ||= Page.first
    @posts = Page.recent(10, channel: 'post')
    @home = Channel.find_by(short_title: 'index')
  end

  def channel
    @channel = Channel.find_by(short_title: params[:id])
    @cases = Page.recent(6, :channel => 'case')
    @relative_posts = @channel.pages.limit(10)
  end

  def posts
    @posts = Channel.find_by(short_title: 'post').pages.page(params[:page])
    @relative_posts = Page.limit(10)
  end

  def post
    @post = params[:id] =~ /^\d+$/ ? Page.find(params[:id]) : Page.find_by(short_title: params[:id])
    @post ||= Page.first
    @relative_posts = Page.limit(10)
  end

  def portfolio
    @posts = Channel.find_by(short_title: 'portfolio').pages.page(params[:page])
    @relative_posts = Page.limit(10)
  end

  def case
    @posts = Channel.find_by(short_title: 'case').pages.page(params[:page])
    # @relative_posts = Page.limit(10)
  end

  def price
  end

  def contact
    @comment = Comment.new
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
    content_for(:title){ [page_title, '直达客'].join('-')}
    return page_title
  end
  def meta_keywords(meta_keywords)
    content_for(:meta_keywords){ [meta_keywords, 'O2O网店，微店建设，O2O营销，产品二维码，企业网站建设，微信公共号开发，百度直达号开发，适配网站建设'].join(',')}
  end
  def meta_description(meta_description)
    content_for(:meta_description){ [meta_description, '直达客平台为企业提供O2O全网营销解决方案，五个产品入口，八大营销模式；精准直达客户，移动你的生意！'].join(',')}
  end

  def get_date(date)
    return if date.blank?
    date.strftime("%Y-%m-%d")
  end

end

app/views/comments/_form.html.erb
<%= simple_form_for(@comment) do |f| %>
  <%= f.error_notification %>

  <%#= f.input :name %>
  <%= f.input :mobile_phone %>
  <%= f.input :content %>
  <br/>
  <%= f.button :submit, class: 'btn btn-large btn-primary' %>  

<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mobile phone</th>
      <th>Email</th>
      <th>Qq</th>
      <th>Address</th>
      <th>Content</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.mobile_phone %></td>
        <td><%= comment.email %></td>
        <td><%= comment.qq %></td>
        <td><%= comment.address %></td>
        <td><%= comment.content %></td>
        <td><%= comment.status %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<% title '联系直达客' %>
<% meta_keywords '网店，微店建设，O2O营销，企业网站建设，微信公共号开发，百度直达号开发，适配网站建设' %>
<% meta_description '直达客平台为企业提供O2O全网营销解决方案，五个产品入口，八大营销模式；从直达客开始，移动你的生意！' %>

<h1>联系我们</h1>

<%= render 'form' %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Mobile phone:</strong>
  <%= @comment.mobile_phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @comment.email %>
</p>

<p>
  <strong>Qq:</strong>
  <%= @comment.qq %>
</p>

<p>
  <strong>Address:</strong>
  <%= @comment.address %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Status:</strong>
  <%= @comment.status %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/about.html.erb
<% title '关于直达客' %>
<% meta_keywords '关于直达客，直达客网站建设，高端品牌网站，多终端网站' %>
<% meta_description '直达客高端品牌网站建设，提供网站、手机网站、小程序开发。直达电话：18080810818' %>

<%= raw Page.find_by(short_title: 'about').try(:content) %>

app/views/home/case.html.erb
<% title '【直达客】成功案例，直达客建站系统！' %>
<% meta_keywords '成功案例，直达客网站建设，直达客手机网站，高端网站设计，网站建设，网页设计，网站运营，公众号，小程序' %>
<% meta_description '网站建设，网页设计，网站运营，公众号，小程序，直达客新一代多终端适配网站建设平台，帮助企业建立网络营销平台，直达电话：18080810818' %>

<!-- Banner -->
<div id="banner-wrapper">
  <div id="banner" class="box container">
    <div class="row">
      <div class="8u">
        <h2>直达客如何帮助企业实现O2O</h2>
        <p>直达客客户遍及家具家居企业、生态农业、洗衣连锁、垂直O2O等行业</p>
      </div>
      <div class="4u">
        <ul>
          <li><a href="/contact" class="button big icon fa-arrow-circle-right">马上联系我们</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<!-- Features -->
<div id="main-wrapper">
  <div class="container">
    <% first = 0 %>
    <% last = 0 %>
    <% @posts.each do |post| %>
      <% if first%3 == 0 %>
        <div class="row">
        <% last = 0 %>
      <% end %>
        <div class="4u">
          <!-- Box -->
          <section class="box feature">
            <a href="<%= post_path(post.short_title)%>" class="image featured"><img src="<%= post.get_image_path %>" alt="<%= post.keywords %>" /></a>
            <div class="inner">
              <header>
                <h2><%= link_to post.title, post_path(post.short_title, from: 'case') %></h2>
                <p><%= post.keywords %></p>
              </header>
              <p><%= post.description %></p>
            </div>
          </section>
        </div>
      <% if last == 2 %>
        </div>
      <% end %>
      <% first += 1 %>
      <% last += 1 %>
    <% end %>
    <div class="row">
      <div class="12u">
        <%= will_paginate @posts %>
      </div>
    </div>
  </div>
</div>

<!-- Main -->
<div id="main-wrapper">
  <div class="container">
    <div class="row 200%">
      <div class="12u">
        <div id="content">

          <div class="row">
            <div class="3u">
              <%=image_tag 'qr-zhidak.png' %>
            </div>
            <div class="3u">
              <p><a href="<%= price_path %>" class="button icon fa-cny"> 价格方案 </a></p>
              <p><a href="<%= contact_path %>" class="button icon fa-user"> 联系我们 </a></p>
            </div>
            <div class="6u">
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/channel.html.erb
<% title @channel.title %>
<% meta_keywords @channel.title %>
<% meta_description @channel.title %>
<!-- Main -->
<div id="main-wrapper">
  <div class="container">
    <div class="row 200%">
      <div class="8u">
        <div id="content">
          <!-- Content -->
          <article>
            <h2><%= @channel.title %></h2>
            <hr/>
            <div class="row">
              <div class="12u">
               <%= @channel.keywords %>
              </div>
            </div>
            <hr/>

            <div class="post-content image fit">
              <%= raw @channel.get_content %>
            </div>
          </article>

        </div>
      </div>
      <div class="4u">
        <%= render 'layouts/sidebar' %>
        <section class="widget thumbnails">
          <h3>他们已经接入直达客</h3>
          <div class="grid">
            <div class="row no-collapse 50%">
              <% @cases.each do |post| %>
                <div class="6u"><a href="<%= post_path(post) %>" class="image fit"><img src="<%= post.get_image_path %>" alt="<%= post.title %>" /></a></div>
              <% end %>
            </div>
          </div>
          <a href="/case" class="button icon fa-file-text-o">查看更多</a>
        </section>
      </div>
    </div>
  </div>
</div>  

app/views/home/index.html.erb
<% title '【直达客】精准直达客户，移动你的生意！网站建设，网页设计，网站运营，公众号，小程序' %>
<% meta_keywords '首页' %>
<% meta_description '网站建设，网页设计，网站运营，公众号，小程序，直达电话：18080810818' %>
<!-- Banner -->
<div id="banner-wrapper">
  <div id="banner" class="box container" style="">
    <div class="row">
      <div class="8u">
        <h2>直达客：高端网站建设平台</h2>
        <p>网站建设＋手机网站＋微信公共号＋小程序＋APP开发</p>
        <small>五大流量入口，让业务精准直达客户！</small>
        <small>八大营销模式，让生意遍布整个网络！</small>
      </div>
      <div class="4u">
        <ul>
          <li><a href="https://static.meiqia.com/dist/standalone.html?eid=1765" class="button big icon fa-comments">移动你的生意</a></li>
          <li><a href="/post/1" class="button blue">了解直达客的开发理念</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<!-- Features -->
<div id="main-wrapper">
  <div class="container">
    <div class="row">
      <% @portfolios.each do |post| %>
        <div class="4u">
          <!-- Box -->
          <section class="box feature">
            <a href="<%= channel_path(post.short_title)%>" class="image featured"><img src="<%= post.get_image_path %>" alt="<%= post.keywords %>" /></a>
            <div class="inner">
              <header class="text-center">
                <h2><%= link_to post.title, channel_path(post.short_title) %></h2>
                <p><%= post.keywords %></p>
              </header>
              <p><%= post.description.truncate(80) %></p>
            </div>
          </section>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- Main -->
<div id="main-wrapper">
  <div class="container">
    <div class="row">
      <div class="4u">
        <!-- Sidebar -->
          <div id="sidebar">
            <section class="widget thumbnails">
              <h3>他们已经接入直达客</h3>
              <div class="grid">
                <div class="row no-collapse 50%">
                  <% (0..1).each do |i|%>
                    <% post = @cases[i] %>
                    <% next if post.nil? %>
                    <div class="6u"><a href="<%= post_path(post) %>" class="image fit"><img src="<%= post.get_image_path %>" alt="<%= post.title %>" /></a></div>
                  <% end %>
                </div>
                <div class="row no-collapse 50%">
                  <% (2..3).each do |i| %>
                    <% post = @cases[i] %>
                    <% next if post.nil? %>
                    <div class="6u"><a href="<%= post_path(post) %>" class="image fit"><img src="<%= post.get_image_path %>" alt="<%= post.title %>" /></a></div>
                  <% end %>
                </div>
                <div class="row no-collapse 50%">
                  <% (4..5).each do |i| %>
                    <% post = @cases[i] %>
                    <% next if post.nil? %>
                    <div class="6u"><a href="<%= post_path(post) %>" class="image fit"><img src="<%= post.get_image_path %>" alt="<%= post.title %>" /></a></div>
                  <% end %>
                </div>
              </div>
              <a href="/case" class="button icon fa-file-text-o">查看更多</a>
            </section>
          </div>
      </div>
      <div class="4u important(collapse)">
          <div id="content">
            <section class="last">
              <h3>直达客行业观点</h3>
              <ul class="style2">
                <% @posts.each do |post| %>
                  <li><i class="icon fa-<%= ['star', 'star-half', 'star-half-o', 'start-o'][rand(3)]%>"></i>   <a href="<%= post_path(post.id) %>"><%= post.title %></a></li>
                <% end %>
              </ul>
            </section>
          </div>
      </div>
      <div class="4u important(collapse)">
        <div id="content">
          <section class="last">
            <h3><%= @about.title %></h3>
            <%= simple_format @about.content.truncate(150) %>
            <a href="<%= post_path(@about) %>" class="button icon fa-arrow-circle-right">了解更多</a>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/portfolio.html.erb
<% title '直达客解决方案' %>
<% meta_keywords '直达客解决方案' %>
<% meta_description '网站建设，网页设计，网站运营，公众号，小程序，直达电话：18080810818' %>

<!-- Main -->
<div id="main-wrapper">
  <div class="container">
    <div class="row 200%">
      <div class="12u">
        <div id="content">
          <% first = 0 %>
          <% last = 0 %>
          <% @posts.each do |post| %>
            <% if first%3 == 0 %>
              <div class="row">
              <% last = 0 %>
            <% end %>
            <div class="4u">
              <!-- Box -->
              <section class="box feature">
                <a href="<%= post_path(post.short_title)%>" class="image featured"><img src="<%= post.get_image_path %>" alt="<%= post.keywords %>" /></a>
                <div class="inner">
                  <header>
                    <h2><%= link_to post.title, post_path(post.short_title) %></h2>
                    <p><%= post.keywords %></p>
                  </header>
                  <p><%= post.description %></p>
                </div>
              </section>
            </div>
            <% if last == 2 %>
              </div>
            <% end %>
            <% first += 1 %>
            <% last += 1 %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="12u">
        <%= will_paginate @posts %>
      </div>
    </div>
  </div>
</div>

app/views/home/posts.html.erb
<% title '直达客全网营销，直达客网站建设，微信小程序服务商！' %>
<% meta_keywords '直达客全网营销，直达客网站建设，微信小程序服务商，移动你的生意，直达你的客户' %>
<% meta_description '直达客全网营销，【直达客】网站建设，微信【官网】小程序服务商，网站建设，网页设计，网站运营，公众号，小程序，电话：18080810818' %>

<!-- Banner -->
<div id="banner-wrapper">
  <div id="banner" class="box container">
    <div class="row">
      <div class="8u">
        <h2>让品牌在浩瀚网络中被点亮！</h2>
        <p>直达客新一代多终端适配建站，配合内容营销策划，让你的品牌脱颖而出！</p>
      </div>
      <div class="4u">
        <ul>
          <li><a href="/contact" class="button big icon fa-arrow-circle-right">马上联系我们</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>


<!-- Main -->
<div id="main-wrapper">
  <div class="container">
    <div class="row">
      <div class="12u">
        <div id="content">
            <% first = 0 %>
            <% last = 0 %>
            <% @posts.each do |post| %>
              <% if first%3 == 0 %>
                <div class="row">
                <% last = 0 %>
              <% end %>
              <div class="4u">
                <!-- Box -->
                <section class="box feature" style="border: solid 1px #f7d2df;">
                  <a href="<%= post_path(post.id)%>" class="image featured"><img src="<%= post.get_image_path %>" alt="<%= post.keywords %>"/></a>
                  <div class="inner">
                    <h2 style="line-height:26px">
                      <%= link_to post.title, post_path(post.short_title) %></h2>
                      <small><%= post.description %></small>
                    <hr/>
                    <p style="color: #000;"><%= post.keywords %></p>
                  </div>
                </section>
              </div>
              <% if last == 2 %>
                </div>
              <% end %>
              <% first += 1 %>
              <% last += 1 %>
            <% end %>
          </div>
          <%= will_paginate @posts %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<% portfolios = Page.recent(10, :channel => 'portfolio') %>
<!-- Footer -->
<div id="footer-wrapper">
  <footer id="footer" class="container">
    <div class="row">
      <div class="3u">

        <!-- Links -->
          <section class="widget links">
            <h3><a href="/portfolio" class="icon fa-cube"> 行业解决方案</a></h3>
            <ul class="style2">
            <% (0..4).each do |i| %>
              <% post = portfolios[i] %>
              <% break if post.nil? %>
              <li><%= link_to post.title, post_path(post) %></li>
            <% end %>
            </ul>
          </section>

      </div>
      <div class="3u">

        <!-- Links -->
          <section class="widget links">
            <h3>&nbsp;</h3>
            <ul class="style2">
              <% (5..9).each do |i| %>
                <% post = portfolios[i] %>
                <% break if post.nil? %>
                <li><%= link_to post.title, post_path(post) %></li>
              <% end %>
              <li><%= link_to '餐饮调味品行业解决方案', 'http://www.meetiao.com' %></li>
            </ul>
          </section>

      </div>
      <div class="3u">
        <% unless mobile_device? %>
        <!-- Links -->
          <section class="widget links">
            <h3><a href="JavaScript:void(0);" class="icon fa-home"> 系列产品</a></h3>
            <ul class="style2">
              <li><a target="_blank" href="http://www.qzhida.com">微信小程序开发：轻直达</a></li>
              <li><a target="_blank" href="http://www.wedxt.com">微场景工具：维斗喜帖</a></li>
              <li><a target="_blank" href="http://www.raincms.cn">CMS建站系统：RainCMS</a></li>
              <li><a target="_blank" href="http://www.zhidat.com">内容营销系统：直达通</a></li>
              <li><a target="_blank" href="http://www.dagle.cn">企业ERP系统：Dagle</a></li>
            </ul>
          </section>
        <% end %>
      </div>
      <div class="3u">
        <!-- Contact -->
          <section class="widget contact last">
            <h3><a href="JavaScript:void(0);" class="icon fa-comments"> 联系我们</a></h3>
            <p><a class="fa fa-arrow-circle-right" href="/about">  关于直达客</a></p>
            <p><a class="fa fa-money" href="/price">  价格方案</a></p>
            <ul>
              <li><a target="_blank" href="https://static.meiqia.com/dist/standalone.html?eid=1765"><span style="color:#fff;">在线</span></a></li>
              <li><a href="http://www.tanmer.com/office" target="_blank"><span style="color:#fff;">定位</span></a></li>
            </ul>
          </section>

      </div>
    </div>
    <div class="row">
      <div class="12u">
        <div id="copyright">
          <ul class="menu">
            <li>&copy; 直达客. <a href="http://www.tanmer.com" target="_blank">成都探码科技有限公司</a>出品</li><li><% unless mobile_device? %>成都市成华区建设北路龙湖三千星座<% end %> </li>
            <li>蜀ICP备14021922号</li>
            <li>
              <!-- cnzz start -->
              <script src="http://s95.cnzz.com/stat.php?id=1254935503&web_id=1254935503" language="JavaScript"></script>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
</div>

app/views/layouts/_header.html.erb
<!-- Header -->
<div id="header-wrapper">
  <header id="header" class="container">

    <!-- Logo -->
    <% unless mobile_device? %>
      <div id="logo" class="hidden-xs">
        <h1><a href="/" title="直达客">直达客</a></h1>
      </div>直达客
    <% end %>

    <!-- Nav -->
      <nav id="nav">
        <ul>
          <li class="<%= 'current' if params[:action] == 'index2' %>"><a href="/">首页</a></li>
          <li class="<%= 'current' if params[:action] == 'case' || params[:from] == 'case' %>"><a href="<%= case_path %>">建站案例</a></li>
          <li class="<%= 'current' if ['posts', 'post'].include? params[:action] %>"><a href="<%= posts_path %>">营销软文</a></li>
          <li><a  href="http://app.zhidat.com" target="_blank">内容自媒体</a></li>
          <li><a href="http://www.tanmer.com/about" target="_blank">联系我们</a></li>
        </ul>
      </nav>

  </header>
</div>

app/views/layouts/_message.html.erb
<%# Rails flash messages styled for Bootstrap 2.3 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <section class="color-bg">
      <div class="text-center alert alert-<%= name.to_s == 'notice' ? "success" : "error" %>">
        <a class="close" data-dismiss="alert">&times;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    </section>
  <% end %>
<% end %>